### ISSUE TITLE
Profile Edit -> About Me

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/Shabbat-Issue-Tracker#314]
When adding a description to the "About me" section, it automatically disappears when I click out of the box, losing whatever was put in the description. 
 
Can you please enforce the "X" to leave that box (or "publish" of course) like you do by messaging?

**Comment by ykoblick** [comment]
I'm still unclear here - I cant replicate this on the website. I don't see an 'X'

**Comment by loebfamily** [comment]
How do I delete a profile?

**Comment by BenzionKlatzko** [comment]
There is an x at the black upper right corner, not in the text box. (in
messaging, there are both x's, the text box and the right corner of the
screen)

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives!
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRzNKgW3Ljs0K2BgXG0W2BFNn256dGkVf8cD4SP02?t=http%3A%2F%2Fwww.shabbat.com%2Fdonate&si=5893560192991232&pi=db8b96a7-b224-489d-e696-88fca6c8f3f1>

**Comment by ykoblick** [comment]
Where in the image below is there a ‘x’:

[cid:image001.png@01D2BDE4.02AEF7E0]

**Comment by BenzionKlatzko** [comment]
Top right corner.


​

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives!
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRzNKgW3Ljs0K2BgXG0W2BFNn256dGkVf8cD4SP02?t=http%3A%2F%2Fwww.shabbat.com%2Fdonate&si=5893560192991232&pi=6d3ed4d7-5ece-44f2-8213-8b4f6c60c26d>
