### ISSUE TITLE
Revisit streaming video

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/Shabbat-Issue-Tracker#334]

**Comment by KodkodGates** [comment]
I was thinking about this at Cloud Conference last week in Javits... Storage of vids & site performance... It won't be cheap depending on your allowance for each users vid uploads. 

![20170606_120927](https://user-images.githubusercontent.com/10193612/27008570-52d9ce62-4e43-11e7-89c8-67f1d155d8d1.jpg)
