### ISSUE TITLE
Message Modal does not scroll down on the profile page.

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/Shabbat-Issue-Tracker#361]
When going to a profile page and clicking the message button, the message thread with previous messages does not scroll down so whatever is not in the Box cannot be seen. This is on a computer. On the message page it works fine.

**Comment by ykoblick** [comment]
Hmm. Was this always the case - I thought we had it right at some point. (Still will fix)

On Jul 12, 2017, at 9:28 PM, BenzionKlatzko <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #361<https://github.com/ykoblick/Shabbat-Issue-Tracker/issues/361> to @ykoblick<https://github.com/ykoblick>.

**Comment by BenzionKlatzko** [comment]
It used to work.

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>
