### ISSUE TITLE
Revamp home page

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/Shabbat-Issue-Tracker#364]

**Comment by ykoblick** [comment]
After showing and speaking over the homepage with the number of people this weekend, here are my thoughts.

1. Can you make the Shabbat.com logo at the top left larger?

2. The 90% look of the image that I sent to you on Friday is the size and layout that looks great. (resending the 90% graphic)

It's interesting that in chrome browser, the 100% or 110% looks too large, but in the Safari browser, the hundred percent looks fine. 

3. People found the letters of the bold font on the bullet points difficult to read. We may have to find a different font.

4. Overall people loved the change!!!!!!!

**Comment by ykoblick** [comment]
<img width="1440" alt="screen shot 2017-07-14 at 6 01 00 pm" src="https://user-images.githubusercontent.com/1099389/28252528-a584b074-6a62-11e7-90c3-44323541436a.png">

**Comment by BenzionKlatzko** [comment]
One more thought. Can you make the logo the yellow orange color of old on
the outer page. If it's large because everything else is white I think it
will stand out. On the inner pages and needed to be white against yellow
background. I'm not 100% sure but I would love to see how it looks with
everything else.

**Comment by ykoblick** [comment]
Soitenly

**Comment by ykoblick** [comment]
Ok - I made some changes. Please review. The only thing I did not yet address is the actual fonts.

**Comment by BenzionKlatzko** [comment]
I think its good!

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>

**Comment by ykoblick** [comment]
What about the font? I can work on that but meanwhile I want it to be sound for mobile and tablets.

Plus I'd like to chop out any unused CSS

On Jul 17, 2017, at 9:30 AM, BenzionKlatzko <notifications@github.com<mailto:notifications@github.com>> wrote:

I think its good!

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com<http://Shabbat.com> - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>

**Comment by BenzionKlatzko** [comment]
Yes. I meant good besides the font. Can you send me a few other possible
font Samples?

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>

**Comment by ykoblick** [comment]
I know it’s a little crazy – but have a look:

https://fonts.google.com/

See if any font captures your attention.
