### ISSUE TITLE
Ester is saying her About Me text disappears

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/Shabbat-Issue-Tracker#371]
Check copy paste

**Comment by ykoblick** [comment]
![image](https://user-images.githubusercontent.com/1099389/28400581-199490b6-6ce2-11e7-914a-5cb63414d09f.png)

**Comment by ykoblick** [comment]
Esther, see the picture I am attaching. I noticed the about section on Internet Exploder is being 'pushed to the bottom'. Is this the possible disapearing issue you are having?

**Comment by ykoblick** [comment]
![image](https://user-images.githubusercontent.com/1099389/28974523-b022ef04-7904-11e7-849f-ed1a3025e3e2.png)

**Comment by estherweis** [comment]
Yehudah,

Thanks for following up. No, it actually was deleted. I use Safari, iPhone
and iPad apps. It wasn't showing on any.

Meantime, it hasn't happened since I last replaced it, about two weeks.

Esther


--
בס"ד
Esther Weis
USA: +1 646.543.9347
Skype: estherweis
estherweis@gmail.com
