### ISSUE TITLE
Mobile Version Home Page Tweaks

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/Shabbat-Issue-Tracker#373]
Remove promo text and place inline controls
to login and a button to register.

Remove menu possibly

Add a button to route to app stores deterministic of platform destination

**Comment by ykoblick** [comment]
Still finish the footer tightening up - with showing/hiding a mobile designed footer

**Comment by BenzionKlatzko** [comment]
Ok

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>

**Comment by ykoblick** [comment]
Ok will check the app logic as well

On Jul 23, 2017, at 11:23 PM, BenzionKlatzko <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com<http://Shabbat.com> - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>
