### ISSUE TITLE
add option to indicate kohen status on dating profile

### ISSUE THREAD

**Issue by estherweis** [ykoblick/Shabbat-Issue-Tracker#374]
#

**Comment by ykoblick** [comment]
Rabbi K. Don't we have this staust 'I am a Cohen'

**Comment by ykoblick** [comment]
Rabbi Klatzko - looking through the code - we 'commented out' the possibility for a member who is orthodox to set whether they are a 'cohen' or not. Effectively for everyone the option is false. I don't recall why we did this. What should we do going forward?

**Comment by BenzionKlatzko** [comment]
I think its worth putting back in. I dont recall why we deleted it.

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>

**Comment by ykoblick** [comment]
![quick-view-add-cohen.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5792811a7d7ca313002a8575/125516c66e82c728ace21e0d46f981932089cebf86eca80ea559f4d92a492f762746ef696097ec22ba416f43554d4bab485a5745fff08f78a7e03c7388540bed846a0a70c63b03b0aac04ee155e57dd205d0f4ae805ec3e93724e28b8f47371a021988f65f36b2d4.jpg)

**Comment by estherweis** [comment]
Awesome, thanks so much!
