### ISSUE TITLE
Restricion Policy amending

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/Shabbat-Issue-Tracker#378]
The primary restriction policy need to include not being able to host request/invite.

The question is does this get added to the messaging restriction or the feed one. 

I forget which is the more comprehensive one. 

I think we should rename to all features restricted.

**Comment by ykoblick** [comment]
Ok – let’s make ‘message restricted’ termed ‘feature restricted’ it will prevent messaging, comments, AND inviting/requesting. Anything else? Should we do guestbook posting and/or dating recommendations?

**Comment by ykoblick** [comment]
Also - I can do a first and last name combination check the same way we look at a black listed email - so when clicking delete & balck list we actually blacklist both the email AND first and last name combination. Thoughts?

**Comment by BenzionKlatzko** [comment]
Thank you. That works!

Warmly and with Joy,

*Benzion Klatzko*
*212-742-2228*


Click Here to Donate to Shabbat.com - Help make a difference in thousands
of people's lives! <http://www.shabbat.com/donate>

**Comment by ykoblick** [comment]
Create a 3rd category called Features_Restricted. This prevents action buttons from apearing at all. Retain the comment restriction with the feed restriction policy.
