### ISSUE TITLE
URL linked shared create broken links

### ISSUE THREAD

**Issue by KodkodGates** [ykoblick/Shabbat-Issue-Tracker#60]
Links shared on newsfeed, are at times, creating broken links not accessible by other users.

**Comment by KodkodGates** [comment]
Yesterday it was a OnlySimchos link... not sure why

Today it was a link with an underscore... http://www.chabad.org/library/article_cdo/aid/2492/jewish/Good-Thinking.htm
which goes instead to "http://www.chabad.org/library/article_"

**Comment by KodkodGates** [comment]
![links still broken](https://cloud.githubusercontent.com/assets/10193612/18478170/3b4f2618-799e-11e6-9222-a43532aa5ddd.JPG)

**Comment by ykoblick** [comment]
Publishing a new build now – should be fixed and ‘closed’ in 5 mins.
